### PR TITLE
fix: remove version from types [SD-438]

### PR DESCRIPTION
**Pull request by chohmann**
We originally wanted version in data for nodes requiring this version properties to be added. We have since changed directions and no longer need these props.

### CODE REVIEW

**Comment by XVincentX** [comment]
I believe this is a breaking change though.

**Comment by chohmann** [comment]
> I believe this is a breaking change though.

How? It was an optional property that I added for a use case that is no longer going to be used.

**Comment by XVincentX** [comment]
Typescript complains when you're putting foreigns undeclared properties. I do not know what software used this, but it's a possibility that could happen. If you were the sole user of `version`, I guess we're fine.

**Comment by chohmann** [comment]
> Typescript complains when you're putting foreigns undeclared properties. I do not know what software used this, but it's a possibility that could happen. If you were the sole user of `version`, I guess we're fine.

Yep! Sole *almost* user. Never even got that far before requirements changed haha.

**Pull request merged**
