### PR TITLE
fix: use tsc to compile the types

### PR DESCRIPTION
**Pull request by XVincentX**
During my changes using this library I noticed that rollup is using for the compilation, and so compiling the project with TSC will result with a broken build that cannot be used. Therefore I was not able to use the `watch` flag to check out the changes on the spot.

Given this library is relatively simple, I think we can avoid to use rollup for this and producing 2-3 different bundles.

1. Publish only the `dist` directory (I saw there were some tests files in the current bundles)
2. Use `tsc` to compile
3. Produce commonjs compatible modules

### CODE REVIEW

**Comment by P0lip** [comment]
> and so compiling the project with TSC will result with a broken build that cannot be used.

Could you elaborate more? You should not end up with a broken build.

**Comment by XVincentX** [comment]
> Could you elaborate more? You should not end up with a broken build.

Basically (took me a while to understand that) TSC was not configured to emit commonjs modules; rollup instead was.

**Comment by P0lip** [comment]
@XVincentX rollup emitted both, but in case of `@stoplight/types` it shouldn't really matter as we consume typings only.

**Comment by XVincentX** [comment]
@P0lip Unfortunately that's not true — the enum we're declaring have a runtime representation, so javascript code is still needed.

**Comment by P0lip** [comment]
@XVincentX true, forgot about enums that are object literals.
That said, what was the problem with Rollup?

**Comment by XVincentX** [comment]
Oh nothing really — I just wanted to solve my problem and I ended up with this branch that I pushed anyway. I'm ok with closing it if does not add any value.

In any case, right now:

1. The published artefact has the `__tests__` directory as well
2. The `typings` field points to a non existing file

**Comment by marbemac** [comment]
I'm cool with this is you can build and then yalc this into graphite and verify everything works.

**Comment by marbemac** [comment]
> The published artefact has the __tests__ directory as well

BTW this might indicate an issue in `sl-scripts`, what do you think @P0lip? Wondering if we're accidentally including __tests__, __stories__, etc folders in the builds for our other libraries that use sl-scripts v7.

**Comment by XVincentX** [comment]
@marbemac @P0lip I confirm it works.

**Comment by P0lip** [comment]
@vncz it only contains typings for tests and stories, so it'd not a big deal

**Comment by XVincentX** [comment]
Up to you folks, I just fixed it locally and pushed a PR for it, if it does not make that much sense feel free to close.

**Comment by XVincentX** [comment]
Never mind I guess

**Pull request merged**
